name: sync-to-dev
on:
  push:
    branches:
      - main
      - feature
jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
         with:
            fetch-depth: 0
       - name: Rebase 
         run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          # git fetch origin
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          echo "Branch name is $BRANCH_NAME!" 
          git checkout dev
          git checkout $BRANCH_NAME
          git rebase dev
          echo "1"
          
          echo "2"
          git checkout dev
          git rebase $BRANCH_NAME
          echo "3"
          git push dev
          echo "4"
